/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar mi perfil
         * @description Devuelve el perfil asociado al sujeto del JWT.
         */
        get: operations["getProfile"];
        /**
         * Actualizar mi perfil
         * @description Reemplaza nombres, apellidos y teléfono del cliente autenticado.
         */
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/addresses/{addressId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reemplazar una dirección */
        put: operations["updateAddress"];
        post?: never;
        /** Eliminar una dirección */
        delete: operations["deleteAddress"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/addresses/{addressId}/primary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Establecer la dirección principal */
        put: operations["setPrimaryAddress"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/items/{cartItemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Actualizar cantidad de un artículo */
        put: operations["updateItem"];
        post?: never;
        /** Quitar artículo del carrito */
        delete: operations["removeItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/publishers/{publisherId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reemplazar editorial */
        put: operations["updatePublisher"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/publishers/{publisherId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambiar el estado de la editorial */
        put: operations["publisherStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/inventory/{editionId}/minimum": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Actualizar mínimo de existencias */
        put: operations["setMinimum"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/editions/{editionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reemplazar edición */
        put: operations["updateEdition"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/editions/{editionId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambiar el estado de la edición */
        put: operations["editionStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/customers/{customerId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambiar el estado de un cliente */
        put: operations["setStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reemplazar categoría */
        put: operations["updateCategory"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories/{categoryId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambiar el estado de la categoría */
        put: operations["categoryStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/books/{bookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reemplazar libro */
        put: operations["updateBook"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/books/{bookId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambiar el estado del libro */
        put: operations["bookStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/authors/{authorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reemplazar autor */
        put: operations["updateAuthor"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/authors/{authorId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambiar el estado del autor */
        put: operations["authorStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancelar un pedido propio
         * @description Si se pierde la respuesta, consulta el detalle del pedido antes de intentar otra cancelación.
         */
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar mis direcciones */
        get: operations["listAddresses"];
        put?: never;
        /** Crear una dirección */
        post: operations["createAddress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalizar compra
         * @description El resultado simulado es determinista. Tras una respuesta desconocida, consulta los pedidos antes de crear otro intento; no reintentes automáticamente.
         */
        post: operations["checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agregar edición al carrito */
        post: operations["addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar una cuenta CUSTOMER
         * @description Aplica BCrypt a la contraseña antes de llamar al procedimiento aprobado de PostgreSQL.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión
         * @description Devuelve un access token bearer HS256 válido durante 30 minutos y establece una cookie HttpOnly de sesión revocable, válida durante 30 días.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/publishers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar editoriales */
        get: operations["searchPublishers"];
        put?: never;
        /** Crear editorial */
        post: operations["createPublisher"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{orderId}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Avanzar el estado logístico del pedido
         * @description Si se pierde la respuesta, consulta el detalle antes de decidir una nueva transición.
         */
        post: operations["transition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancelar un pedido elegible
         * @description Si se pierde la respuesta, consulta el detalle del pedido antes de repetir.
         */
        post: operations["cancel_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/inventory/{editionId}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar ingreso de inventario */
        post: operations["entry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/inventory/{editionId}/adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ajustar existencias */
        post: operations["adjust"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/editions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar ediciones */
        get: operations["searchEditions"];
        put?: never;
        /** Crear edición */
        post: operations["createEdition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar categorías */
        get: operations["searchCategories"];
        put?: never;
        /** Crear categoría */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar libros */
        get: operations["searchBooks"];
        put?: never;
        /** Crear libro */
        post: operations["createBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar autores */
        get: operations["searchAuthors"];
        put?: never;
        /** Crear autor */
        post: operations["createAuthor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/transfer-details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["transferDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["countries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar pedidos propios
         * @description Ordenados por fecha de creación y número de pedido descendentes.
         */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar detalle de un pedido propio */
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/filter-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar opciones de filtros del catálogo público
         * @description Devuelve los idiomas y límites de precio de las ediciones publicables actuales.
         */
        get: operations["filterOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/editions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar ediciones publicables
         * @description Filtra y pagina el catálogo público. Un slug de categoría desconocido devuelve una página vacía; una categoría inactiva devuelve 409.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/editions/{editionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar una edición publicable */
        get: operations["getEdition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar categorías del catálogo público
         * @description Devuelve categorías activas con ediciones publicables y su jerarquía de hasta dos niveles.
         */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar carrito activo */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar pedidos
         * @description Filtros y orden definidos por fn_admin_orders.
         */
        get: operations["search_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar detalle administrativo de un pedido */
        get: operations["detail_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar inventario */
        get: operations["search_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/inventory/{editionId}/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar movimientos de inventario */
        get: operations["movements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar clientes */
        get: operations["search_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restaurar o renovar la sesión
         * @description Rota la credencial persistente HttpOnly y emite un access token nuevo. Si se pierde la respuesta, repetir con la cookie anterior durante 5 minutos devuelve la misma rotación. La sesión vence de forma absoluta a los 30 días del inicio de sesión.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cerrar sesión
         * @description Revoca la sesión persistente en PostgreSQL y elimina la cookie HttpOnly. La operación es idempotente.
         */
        post: operations["logoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Reemplaza los datos mutables del perfil CUSTOMER. */
        ProfileUpdateRequest: {
            /** @example Ana María */
            firstNames: string;
            /** @example Pérez López */
            lastNames: string;
            /** @example +59325550134 */
            phone?: string | null;
        };
        /** @description Detalle de problema RFC 9457 con campos de correlación de PLIEGO. */
        ProblemDetail: {
            /**
             * Format: uri
             * @example urn:pliego:problem:VALIDATION_ERROR
             */
            type?: string;
            /** @example Datos inválidos */
            title?: string;
            /**
             * Format: int32
             * @example 400
             */
            status?: number;
            /** @example Revisa los datos enviados e intenta nuevamente. */
            detail?: string;
            /**
             * Format: uri
             * @example /api/v1/auth/register
             */
            instance?: string;
            /**
             * @description Código estable legible por máquina. Los errores de dominio usan el SQLSTATE canónico de PostgreSQL (Pxxxx); los errores propios de la capa REST usan un código simbólico (por ejemplo VALIDATION_ERROR o INVALID_CARD_NUMBER).
             * @example P3002
             */
            code?: string;
            /** @example 8f2ab598-3e33-40b1-a5c7-15f676a84f9a */
            traceId?: string;
        };
        /** @description Reemplaza todos los datos mutables de la dirección. */
        AddressUpdateRequest: {
            /** @example Casa */
            alias: string;
            /** @example Ana Pérez */
            recipient: string;
            /** @example Av. Principal 123 */
            line1: string;
            /** @example Departamento 4 */
            line2?: string | null;
            /** @example Quito */
            city: string;
            /** @example Pichincha */
            province: string;
            /** @example EC */
            countryCode: string;
            /** @example 170101 */
            postalCode?: string | null;
            /** @example Frente al parque */
            reference?: string | null;
            /** @example +59325550134 */
            phone: string;
        };
        Quantity: {
            /** Format: int32 */
            quantity: number;
        };
        ItemMutation: {
            cartId?: string;
            cartItemId?: string;
            /** Format: int32 */
            quantity?: number;
        };
        Publisher: {
            publisherId?: string;
            name?: string;
        };
        Status: {
            state: string;
        };
        Minimum: {
            /** Format: int32 */
            stockMinimum: number;
        };
        EditionUpdate: {
            publisherId: string;
            isbn13?: string;
            language: string;
            format: string;
            /** Format: int32 */
            pageCount: number;
            /** Format: date */
            publicationDate?: string;
            price: string;
            coverUrl?: string;
            coverLicense?: string;
            coverSourceUrl?: string;
            coverAttribution?: string;
        };
        Category: {
            slug?: string;
            name?: string;
            parentSlug?: string;
        };
        AuthorAssignment: {
            authorId: string;
            /** Format: int32 */
            order: number;
        };
        Book: {
            title: string;
            subtitle?: string;
            synopsis?: string;
            authors: components["schemas"]["AuthorAssignment"][];
            categoryIds: string[];
        };
        Author: {
            authorId?: string;
            name?: string;
            /** Format: int32 */
            order?: number;
        };
        Cancellation: {
            orderId?: string;
            previousState?: string;
            orderState?: string;
            paymentState?: string;
            /** Format: int64 */
            restoredUnits?: number;
        };
        /** @description Datos completos de una dirección del cliente. */
        AddressRequest: {
            /** @example Casa */
            alias: string;
            /** @example Ana Pérez */
            recipient: string;
            /** @example Av. Principal 123 */
            line1: string;
            /** @example Departamento 4 */
            line2?: string | null;
            /** @example Quito */
            city: string;
            /** @example Pichincha */
            province: string;
            /** @example EC */
            countryCode: string;
            /** @example 170101 */
            postalCode?: string | null;
            /** @example Frente al parque */
            reference?: string | null;
            /** @example +59325550134 */
            phone: string;
            /** @example true */
            makePrimary: boolean;
        };
        AddressCreated: {
            /** @example 15 */
            addressId?: string;
        };
        CheckoutRequest: {
            addressId: string;
            paymentMethod: string;
            simulationOutcome: string;
            /** @description Se valida localmente y nunca se persiste ni se envía a PostgreSQL. */
            cardNumber?: string;
        };
        CheckoutResponse: {
            orderId?: string;
            orderState?: string;
            paymentState?: string;
            total?: string;
            paymentReference?: string;
        };
        AddItem: {
            editionId: string;
            /** Format: int32 */
            quantity: number;
        };
        /** @description Crea una cuenta CUSTOMER activa. */
        RegisterRequest: {
            /**
             * Format: email
             * @example usuario@example.com
             */
            email: string;
            /**
             * Format: password
             * @description Al menos 8 caracteres Unicode y máximo 72 bytes en UTF-8.
             * @example password-segura
             */
            password: string;
            /** @example Ana María */
            firstNames: string;
            /** @example Pérez López */
            lastNames: string;
            /** @example +59325550134 */
            phone?: string | null;
        };
        RegisterResponse: {
            /** @example 100 */
            userId?: string;
            /** @example 87 */
            customerId?: string;
            /**
             * @example ACTIVE
             * @enum {string}
             */
            state?: "ACTIVE";
        };
        LoginRequest: {
            /**
             * Format: email
             * @example usuario@example.com
             */
            email: string;
            /**
             * Format: password
             * @description Máximo 72 bytes en UTF-8.
             */
            password: string;
        };
        AuthenticatedUser: {
            /** @example 100 */
            userId?: string;
            /** @example usuario@example.com */
            email?: string;
            /**
             * @example CUSTOMER
             * @enum {string}
             */
            role?: "CUSTOMER" | "ADMIN";
        };
        LoginResponse: {
            /** Format: jwt */
            accessToken?: string;
            /** @example Bearer */
            tokenType?: string;
            /**
             * Format: int32
             * @example 1800
             */
            expiresInSeconds?: number;
            user?: components["schemas"]["AuthenticatedUser"];
        };
        PublisherCreated: {
            publisherId?: string;
        };
        Transition: {
            targetState: string;
        };
        Entry: {
            /** Format: int32 */
            quantity: number;
            reason: string;
        };
        MovementCreated: {
            movementId?: string;
            /** Format: int32 */
            stockBefore?: number;
            /** Format: int32 */
            stockAfter?: number;
        };
        Adjustment: {
            type: string;
            /** Format: int32 */
            quantity: number;
            reason: string;
        };
        EditionCreate: {
            bookId: string;
            publisherId: string;
            sku: string;
            isbn13?: string;
            language: string;
            format: string;
            /** Format: int32 */
            pageCount: number;
            /** Format: date */
            publicationDate?: string;
            price: string;
            coverUrl?: string;
            coverLicense?: string;
            coverSourceUrl?: string;
            coverAttribution?: string;
        };
        EditionCreated: {
            editionId?: string;
        };
        CategoryCreated: {
            categoryId?: string;
        };
        BookCreated: {
            bookId?: string;
        };
        AuthorCreated: {
            authorId?: string;
        };
        TransferDetails: {
            bank?: string;
            beneficiary?: string;
            accountType?: string;
            accountNumber?: string;
            identification?: string;
        };
        Country: {
            code?: string;
            name?: string;
        };
        PageResponse: {
            items?: unknown[];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            totalCount?: string;
        };
        Address: {
            recipient?: string;
            line1?: string;
            line2?: string;
            city?: string;
            province?: string;
            countryCode?: string;
            postalCode?: string;
            reference?: string;
            phone?: string;
        };
        Detail: {
            orderId?: string;
            orderState?: string;
            subtotal?: string;
            total?: string;
            createdAt?: string;
            updatedAt?: string;
            items?: components["schemas"]["Item"][];
            address?: components["schemas"]["Address"];
            payment?: components["schemas"]["Payment"];
            stateHistory?: components["schemas"]["History"][];
        };
        History: {
            historyId?: string;
            actorUserId?: string;
            origin?: string;
            previousState?: string;
            newState?: string;
            at?: string;
        };
        Item: {
            orderItemId?: string;
            editionId?: string;
            sku?: string;
            isbn?: string;
            title?: string;
            authors?: string;
            publisher?: string;
            format?: string;
            language?: string;
            unitPrice?: string;
            /** Format: int32 */
            quantity?: number;
            subtotal?: string;
        };
        Payment: {
            paymentId?: string;
            method?: string;
            state?: string;
            amount?: string;
            reference?: string;
            resultDetail?: string;
            createdAt?: string;
            updatedAt?: string;
        };
        CustomerProfile: {
            /** @example 87 */
            customerId?: string;
            /** @example usuario@example.com */
            email?: string;
            /** @example Ana María */
            firstNames?: string;
            /** @example Pérez López */
            lastNames?: string;
            /** @example +59325550134 */
            phone?: string | null;
            /**
             * @example ACTIVE
             * @enum {string}
             */
            state?: "ACTIVE" | "BLOCKED";
        };
        CustomerAddress: {
            /** @example 15 */
            addressId?: string;
            /** @example Casa */
            alias?: string;
            /** @example Ana Pérez */
            recipient?: string;
            /** @example Av. Principal 123 */
            line1?: string;
            /** @example Departamento 4 */
            line2?: string | null;
            /** @example Quito */
            city?: string;
            /** @example Pichincha */
            province?: string;
            /** @example EC */
            countryCode?: string;
            /** @example 170101 */
            postalCode?: string | null;
            /** @example Frente al parque */
            reference?: string | null;
            /** @example +59325550134 */
            phone?: string;
            /** @example true */
            primary?: boolean;
        };
        PublicCatalogFilterOptionsResponse: {
            languages?: string[];
            minimumPrice?: string | null;
            maximumPrice?: string | null;
        };
        CatalogEditionSearchResponse: {
            items?: components["schemas"]["CatalogEditionSummaryResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            totalCount?: string;
        };
        CatalogEditionSummaryResponse: {
            editionId?: string;
            bookId?: string;
            title?: string;
            authors?: string;
            publisher?: string;
            isbn13?: string;
            price?: string;
            coverUrl?: string | null;
            coverLicense?: string | null;
            coverAttribution?: string | null;
            format?: string;
            language?: string;
            available?: boolean;
        };
        CatalogEditionDetailResponse: {
            editionId?: string;
            bookId?: string;
            title?: string;
            subtitle?: string;
            synopsis?: string | null;
            authors?: components["schemas"]["Author"][];
            categories?: components["schemas"]["Category"][];
            publisher?: components["schemas"]["Publisher"];
            isbn13?: string;
            sku?: string;
            language?: string;
            format?: string;
            /** Format: int32 */
            pageCount?: number;
            publicationDate?: string;
            price?: string;
            coverUrl?: string | null;
            coverLicense?: string | null;
            coverSourceUrl?: string | null;
            coverAttribution?: string | null;
            available?: boolean;
        };
        CatalogCategoryListResponse: {
            items?: components["schemas"]["Category"][];
        };
        Cart: {
            cartId?: string | null;
            state?: string | null;
            items?: components["schemas"]["CartItem"][];
            totalCurrent?: string;
        };
        CartItem: {
            cartItemId?: string;
            editionId?: string;
            title?: string;
            authors?: string;
            sku?: string;
            coverUrl?: string | null;
            /** Format: int32 */
            quantity?: number;
            currentPrice?: string;
            currentSubtotal?: string;
            available?: boolean;
            /**
             * @description SQLSTATE canónico de la condición que impide comprar el artículo: P2043 libro inactivo, P2042 edición inactiva, P3002 existencias insuficientes; null si está disponible.
             * @example P3002
             * @enum {string|null}
             */
            unavailabilityReason?: "P2043" | "P2042" | "P3002" | null;
        };
        PageResponsePublisher: {
            items?: components["schemas"]["Publisher"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            totalCount?: string;
        };
        PageResponseItem: {
            items?: components["schemas"]["Item"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            totalCount?: string;
        };
        Movement: {
            movementId?: string;
            editionId?: string;
            orderId?: string;
            actorUserId?: string;
            type?: string;
            /** Format: int32 */
            quantity?: number;
            /** Format: int32 */
            stockBefore?: number;
            /** Format: int32 */
            stockAfter?: number;
            reason?: string;
            eventAt?: string;
        };
        PageResponseMovement: {
            items?: components["schemas"]["Movement"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            totalCount?: string;
        };
        Edition: {
            editionId?: string;
            bookId?: string;
            bookTitle?: string;
            publisherId?: string;
            publisherName?: string;
            sku?: string;
            isbn13?: string;
            language?: string;
            format?: string;
            /** Format: int32 */
            pageCount?: number;
            publicationDate?: string;
            price?: string;
            coverUrl?: string;
            coverLicense?: string;
            coverSourceUrl?: string;
            coverAttribution?: string;
            state?: string;
            /** Format: int32 */
            stockActual?: number;
            createdAt?: string;
            updatedAt?: string;
        };
        PageResponseEdition: {
            items?: components["schemas"]["Edition"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            totalCount?: string;
        };
        CustomerSummary: {
            customerId?: string;
            email?: string;
            firstNames?: string;
            lastNames?: string;
            phone?: string;
            state?: string;
            createdAt?: string;
        };
        PageResponseCustomerSummary: {
            items?: components["schemas"]["CustomerSummary"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            totalCount?: string;
        };
        PageResponseCategory: {
            items?: components["schemas"]["Category"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            totalCount?: string;
        };
        PageResponseBook: {
            items?: components["schemas"]["Book"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            totalCount?: string;
        };
        PageResponseAuthor: {
            items?: components["schemas"]["Author"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            totalCount?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil del cliente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
            /** @description Autenticación inválida */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Perfil actualizado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Datos inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    updateAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                addressId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressUpdateRequest"];
            };
        };
        responses: {
            /** @description Dirección actualizada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dirección no disponible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    deleteAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                addressId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dirección eliminada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dirección no disponible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    setPrimaryAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                addressId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dirección principal establecida */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dirección no disponible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cartItemId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Quantity"];
            };
        };
        responses: {
            /** @description Artículo actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemMutation"];
                };
            };
            /** @description Solicitud inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    removeItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cartItemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artículo eliminado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Artículo no encontrado en el carrito */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    updatePublisher: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publisherId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Publisher"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    publisherStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publisherId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Status"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setMinimum: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                editionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Minimum"];
            };
        };
        responses: {
            /** @description Mínimo actualizado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateEdition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                editionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditionUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    editionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                editionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Status"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Status"];
            };
        };
        responses: {
            /** @description Estado actualizado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cliente no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Category"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    categoryStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Status"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Book"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bookStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Status"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAuthor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                authorId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Author"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authorStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                authorId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Status"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pedido cancelado y pago reembolsado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cancellation"];
                };
            };
            /** @description Pedido no disponible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Pedido no cancelable */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    listAddresses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Direcciones ordenadas según el contrato */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerAddress"][];
                };
            };
        };
    };
    createAddress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressRequest"];
            };
        };
        responses: {
            /** @description Dirección creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressCreated"];
                };
            };
            /** @description Datos inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    checkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Pedido creado, con pago aprobado o rechazado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"];
                };
            };
            /** @description Solicitud inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    addItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddItem"];
            };
        };
        responses: {
            /** @description Carrito y artículo actualizados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemMutation"];
                };
            };
            /** @description Solicitud inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Cuenta de cliente creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Datos inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Correo ya registrado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error interno */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Token de acceso emitido y sesión persistente establecida */
            200: {
                headers: {
                    /** @description Cookie HttpOnly, Secure, SameSite=Strict; expira 30 días después del inicio de sesión. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Datos inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Credenciales inválidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error interno */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    searchPublishers: {
        parameters: {
            query?: {
                query?: string;
                state?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponsePublisher"];
                };
            };
        };
    };
    createPublisher: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Publisher"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublisherCreated"];
                };
            };
        };
    };
    transition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transition"];
            };
        };
        responses: {
            /** @description Transición registrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transition"];
                };
            };
            /** @description Pedido no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Transición no permitida */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    cancel_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pedido cancelado y pago reembolsado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cancellation"];
                };
            };
            /** @description Pedido no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Pedido no cancelable */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    entry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                editionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Entry"];
            };
        };
        responses: {
            /** @description Ingreso registrado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementCreated"];
                };
            };
        };
    };
    adjust: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                editionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Adjustment"];
            };
        };
        responses: {
            /** @description Ajuste registrado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementCreated"];
                };
            };
        };
    };
    searchEditions: {
        parameters: {
            query?: {
                query?: string;
                state?: string;
                bookId?: number;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseEdition"];
                };
            };
        };
    };
    createEdition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditionCreate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditionCreated"];
                };
            };
        };
    };
    searchCategories: {
        parameters: {
            query?: {
                query?: string;
                state?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseCategory"];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Category"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryCreated"];
                };
            };
        };
    };
    searchBooks: {
        parameters: {
            query?: {
                query?: string;
                state?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseBook"];
                };
            };
        };
    };
    createBook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Book"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookCreated"];
                };
            };
        };
    };
    searchAuthors: {
        parameters: {
            query?: {
                query?: string;
                state?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de autores */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseAuthor"];
                };
            };
            /** @description Filtros inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    createAuthor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Author"];
            };
        };
        responses: {
            /** @description Autor creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorCreated"];
                };
            };
        };
    };
    transferDetails: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferDetails"];
                };
            };
        };
    };
    countries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Country"][];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de pedidos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalle completo del pedido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            /** @description Pedido no disponible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    filterOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Opciones disponibles para los filtros del catálogo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicCatalogFilterOptionsResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                /** @description Texto parcial del título */
                title?: string;
                /** @description Texto parcial del autor */
                author?: string;
                isbn13?: string;
                category?: string;
                minPrice?: number;
                maxPrice?: number;
                language?: string;
                format?: string;
                sort?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página del catálogo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogEditionSearchResponse"];
                };
            };
            /** @description Filtros inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description La categoría está inactiva */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getEdition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                editionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalle de la edición */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogEditionDetailResponse"];
                };
            };
            /** @description Edición no disponible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categorías disponibles para navegar el catálogo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogCategoryListResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Carrito activo o representación vacía */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
        };
    };
    search_1: {
        parameters: {
            query?: {
                state?: string;
                dateFrom?: string;
                dateTo?: string;
                customerId?: number;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de pedidos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
        };
    };
    detail_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pedido con snapshots, historial y movimientos relacionados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            /** @description Pedido no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    search_2: {
        parameters: {
            query?: {
                editionId?: number;
                title?: string;
                sku?: string;
                lowStockOnly?: boolean;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de inventario */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseItem"];
                };
            };
            /** @description Filtros inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    movements: {
        parameters: {
            query?: {
                type?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                editionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historial de movimientos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseMovement"];
                };
            };
        };
    };
    search_3: {
        parameters: {
            query?: {
                query?: string;
                state?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de clientes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseCustomerSummary"];
                };
            };
            /** @description Filtros inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header: {
                /** @description Marcador requerido para autorizar la petición de sesión desde el cliente PLIEGO. */
                "X-PLIEGO-SESSION-REQUEST": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión restaurada */
            200: {
                headers: {
                    /** @description Cookie HttpOnly renovada; conserva la expiración absoluta de la sesión. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description No existe una sesión válida; se elimina la cookie */
            204: {
                headers: {
                    /** @description Cookie eliminada. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error interno */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    logoutSession: {
        parameters: {
            query?: never;
            header: {
                /** @description Marcador requerido para autorizar la petición de sesión desde el cliente PLIEGO. */
                "X-PLIEGO-SESSION-REQUEST": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión revocada y cookie eliminada */
            204: {
                headers: {
                    /** @description Cookie eliminada. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error interno */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
