import type { EditionSummary } from "@/shared/api/catalog";

// Bibliography/CDN URLs: committed covers staging and normalized manifest.
// IDs are diagnostic-only. Price/availability use the development seed defaults.
export const bookCardFixtures = [
  {
    "editionId": "9000001",
    "bookId": "8000001",
    "title": "El extranjero",
    "authors": "Albert Camus",
    "publisher": "Booket",
    "isbn13": "9786070738548",
    "price": "20.00",
    "coverUrl": "https://covers.pliegolibros.com/covers/editions/v2/PLG-BK-000002-ca452ee580f4.webp",
    "coverLicense": null,
    "coverAttribution": null,
    "format": "PAPERBACK",
    "language": "es",
    "available": true
  },
  {
    "editionId": "9000002",
    "bookId": "8000002",
    "title": "Cien años de soledad",
    "authors": "Gabriel García Márquez",
    "publisher": "Debolsillo",
    "isbn13": "9786287745131",
    "price": "20.00",
    "coverUrl": "https://covers.pliegolibros.com/covers/editions/v2/PLG-BK-000014-b456b439611b.webp",
    "coverLicense": null,
    "coverAttribution": null,
    "format": "HARDCOVER",
    "language": "es",
    "available": true
  },
  {
    "editionId": "9000003",
    "bookId": "8000003",
    "title": "Anna Karénina",
    "authors": "Lev Tolstói",
    "publisher": "Salamandra",
    "isbn13": "9788478883608",
    "price": "20.00",
    "coverUrl": "https://covers.pliegolibros.com/covers/editions/v2/PLG-BK-000035-b62b28e2ae01.webp",
    "coverLicense": null,
    "coverAttribution": null,
    "format": "PAPERBACK",
    "language": "es",
    "available": true
  },
  {
    "editionId": "9000004",
    "bookId": "8000004",
    "title": "Introducción al álgebra lineal",
    "authors": "José Alfredo Collazos Sánchez, Carlos Alberto Ramírez Vanegas, Óscar Danilo Montoya Giraldo",
    "publisher": "Ecoe Ediciones",
    "isbn13": "9789585082656",
    "price": "20.00",
    "coverUrl": "https://covers.pliegolibros.com/covers/editions/v2/PLG-BK-000044-204968142c57.webp",
    "coverLicense": null,
    "coverAttribution": null,
    "format": "PAPERBACK",
    "language": "es",
    "available": true
  },
  {
    "editionId": "9000005",
    "bookId": "8000005",
    "title": "Inferencia bayesiana y el método de máxima entropía",
    "authors": "Juan Esteban Jacobo Vásquez",
    "publisher": "Universidad Externado de Colombia",
    "isbn13": "9789585062665",
    "price": "20.00",
    "coverUrl": "https://covers.pliegolibros.com/covers/editions/v2/PLG-BK-000043-eb2957751239.webp",
    "coverLicense": null,
    "coverAttribution": null,
    "format": "PAPERBACK",
    "language": "es",
    "available": true
  },
  {
    "editionId": "9000006",
    "bookId": "8000006",
    "title": "Los miserables",
    "authors": "Victor Hugo",
    "publisher": "Plutón Ediciones",
    "isbn13": "9791387692865",
    "price": "20.00",
    "coverUrl": "https://covers.pliegolibros.com/covers/editions/v2/PLG-BK-000054-fe0fdb7fdd82.webp",
    "coverLicense": null,
    "coverAttribution": null,
    "format": "HARDCOVER",
    "language": "es",
    "available": true
  },
  {
    "editionId": "9000007",
    "bookId": "8000007",
    "title": "Ecuaciones diferenciales y problemas con valores en la frontera",
    "authors": "William E. Boyce, Richard C. DiPrima",
    "publisher": "Limusa Wiley",
    "isbn13": "9789681849740",
    "price": "20.00",
    "coverUrl": "https://covers.pliegolibros.com/covers/editions/v2/PLG-BK-000047-aa33471e3d31.webp",
    "coverLicense": null,
    "coverAttribution": null,
    "format": "PAPERBACK",
    "language": "es",
    "available": true
  },
  {
    "editionId": "9000008",
    "bookId": "8000008",
    "title": "Ecuaciones diferenciales y problemas con valores en la frontera",
    "authors": "R. Kent Nagle, Edward B. Saff, Arthur David Snider",
    "publisher": "Pearson Educación",
    "isbn13": "9789702605928",
    "price": "20.00",
    "coverUrl": "https://covers.pliegolibros.com/covers/editions/v2/PLG-BK-000049-ff9728f0ddef.webp",
    "coverLicense": null,
    "coverAttribution": null,
    "format": "PAPERBACK",
    "language": "es",
    "available": true
  },
  {
    "editionId": "9000009",
    "bookId": "8000009",
    "title": "Métodos numéricos aplicados a la ingeniería",
    "authors": "Antonio Nieves Hurtado, Federico C. Domínguez Sánchez",
    "publisher": "Compañía Editorial Continental",
    "isbn13": "9789702402589",
    "price": "20.00",
    "coverUrl": "https://covers.pliegolibros.com/covers/editions/v2/PLG-BK-000048-3f3528aa2b7d.webp",
    "coverLicense": null,
    "coverAttribution": null,
    "format": "PAPERBACK",
    "language": "es",
    "available": true
  },
  {
    "editionId": "9000010",
    "bookId": "8000010",
    "title": "La genealogía de la moral",
    "authors": "Friedrich Nietzsche",
    "publisher": "Plutón Ediciones",
    "isbn13": "9788419651730",
    "price": "20.00",
    "coverUrl": "https://covers.pliegolibros.com/covers/editions/v2/PLG-BK-000026-26fcbd0dabe9.webp",
    "coverLicense": null,
    "coverAttribution": null,
    "format": "PAPERBACK",
    "language": "es",
    "available": true
  },
  {
    "editionId": "9000011",
    "bookId": "8000011",
    "title": "Análisis matemático",
    "authors": "Tom M. Apostol",
    "publisher": "Editorial Reverté",
    "isbn13": "9788429150049",
    "price": "20.00",
    "coverUrl": "https://covers.pliegolibros.com/covers/editions/v2/PLG-BK-000028-5c3053a00867.webp",
    "coverLicense": null,
    "coverAttribution": null,
    "format": "PAPERBACK",
    "language": "es",
    "available": true
  },
  {
    "editionId": "9000012",
    "bookId": "8000012",
    "title": "Análisis matemático I",
    "authors": "Moisés Lázaro Carrión",
    "publisher": "Moshera",
    "isbn13": "9789972813818",
    "price": "20.00",
    "coverUrl": "https://covers.pliegolibros.com/covers/editions/v2/PLG-BK-000052-b80e012ee00e.webp",
    "coverLicense": null,
    "coverAttribution": null,
    "format": "PAPERBACK",
    "language": "es",
    "available": true
  }
] satisfies EditionSummary[];
