CREATE UNIQUE INDEX uqx_direccion_cliente_principal ON pliego.direccion(cliente_id) WHERE es_principal;
CREATE INDEX idx_direccion_cliente ON pliego.direccion(cliente_id);
CREATE INDEX idx_categoria_padre ON pliego.categoria(categoria_padre_id) WHERE categoria_padre_id IS NOT NULL;
CREATE INDEX idx_libro_autor_autor ON pliego.libro_autor(autor_id,libro_id);
CREATE INDEX idx_libro_categoria_categoria ON pliego.libro_categoria(categoria_id,libro_id);
CREATE INDEX idx_edicion_libro ON pliego.edicion(libro_id,edicion_id);
CREATE INDEX idx_edicion_editorial ON pliego.edicion(editorial_id,edicion_id);
CREATE INDEX idx_edicion_catalogo_filtros ON pliego.edicion(estado,idioma,formato,precio,edicion_id);
CREATE UNIQUE INDEX uqx_carrito_cliente_active ON pliego.carrito(cliente_id) WHERE estado='ACTIVE';
CREATE INDEX idx_carrito_cliente_fecha ON pliego.carrito(cliente_id,fecha_creacion DESC,carrito_id DESC);
CREATE INDEX idx_carrito_item_edicion ON pliego.carrito_item(edicion_id,carrito_id);
CREATE INDEX idx_pedido_cliente_fecha ON pliego.pedido(cliente_id,fecha_creacion DESC,pedido_id DESC);
CREATE INDEX idx_pedido_estado_fecha ON pliego.pedido(estado,fecha_creacion DESC,pedido_id DESC);
CREATE INDEX idx_pedido_fecha ON pliego.pedido(fecha_creacion DESC,pedido_id DESC);
CREATE INDEX idx_pedido_item_edicion ON pliego.pedido_item(edicion_id,pedido_id);
CREATE UNIQUE INDEX uqx_pedido_historial_inicial ON pliego.pedido_estado_historial(pedido_id) WHERE estado_anterior IS NULL;
CREATE INDEX idx_pedido_historial_pedido_fecha ON pliego.pedido_estado_historial(pedido_id,fecha ASC,pedido_estado_historial_id ASC);
CREATE UNIQUE INDEX uqx_movimiento_pedido_edicion_tipo ON pliego.movimiento_inventario(pedido_id,edicion_id,tipo) WHERE tipo IN ('SALE','CANCELLATION');
CREATE INDEX idx_movimiento_edicion_fecha ON pliego.movimiento_inventario(edicion_id,fecha DESC,movimiento_inventario_id DESC);
CREATE INDEX idx_movimiento_pedido ON pliego.movimiento_inventario(pedido_id) WHERE pedido_id IS NOT NULL;
