BEGIN;
DO $gate$
DECLARE a BIGINT; u BIGINT; customer BIGINT; author_id BIGINT; pub BIGINT; cat BIGINT; book BIGINT; facet_parent BIGINT; facet_child BIGINT;
 edition BIGINT; digital BIGINT; movement BIGINT; stock_before INTEGER; stock_after INTEGER; cart BIGINT; item BIGINT; qty INTEGER;
 address BIGINT; offer BIGINT; o BIGINT; replay BIGINT; location BIGINT; state VARCHAR; pay VARCHAR; total NUMERIC; ref VARCHAR;
 key UUID:=uuidv4(); quote RECORD; projection RECORD;
BEGIN
 INSERT INTO pliego.usuario(email_normalizado,password_hash,rol,estado) VALUES('offers-admin@example.invalid','fixture','ADMIN','ACTIVE') RETURNING usuario_id INTO a;
 CALL pliego.sp_author_create(a,'Autora ofertas',NULL,author_id);
 CALL pliego.sp_publisher_create(a,'Editorial ofertas',NULL,pub);
 CALL pliego.sp_category_create(a,'Ofertas','offers-gate',NULL,NULL,cat);
 CALL pliego.sp_book_create(a,'Libro ofertas',NULL,NULL,jsonb_build_array(jsonb_build_object('authorId',author_id,'order',1)),jsonb_build_array(cat),book);
 CALL pliego.sp_customer_register('offers-customer@example.invalid','fixture','Ana','Pérez',NULL,u,customer,state);
 CALL pliego.sp_edition_create(a,book,pub,'OFFERS-PHYSICAL',NULL,'es','PAPERBACK',100,NULL,20.00,NULL,NULL,NULL,NULL,edition);
 CALL pliego.sp_inventory_entry(a,edition,10,'fixture',movement,stock_before,stock_after);
 CALL pliego.sp_edition_offer_set(a,edition,15.00,statement_timestamp()-INTERVAL '1 day',statement_timestamp()+INTERVAL '1 day',offer);
 SELECT * INTO projection FROM pliego.fn_edition_offer(edition);
 IF projection.days_remaining<>1 OR NOT projection.ending_soon THEN RAISE EXCEPTION 'calendar-day offer projection incorrect'; END IF;
 IF projection.savings_percent<>25.00 THEN RAISE EXCEPTION 'offer savings percentage incorrect'; END IF;
 IF projection.price<>15.00 OR projection.original_price<>20.00 OR projection.discount_amount<>5.00 OR projection.offer_id<>offer THEN RAISE EXCEPTION 'offer projection incorrect'; END IF;
 IF (SELECT price FROM pliego.fn_catalog_search(NULL,NULL,NULL,'offers-gate',14,16,NULL,NULL,'PRICE_ASC',0,20) WHERE edition_id=edition)<>15.00 THEN RAISE EXCEPTION 'effective catalog filter price incorrect'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pliego.fn_catalog_search_offers(NULL,NULL,NULL,'offers-gate',NULL,NULL,NULL,NULL,NULL,'RELEVANCE',0,20) WHERE edition_id=edition AND total_count=1) THEN RAISE EXCEPTION 'offer catalog pagination incorrect'; END IF;
 BEGIN
  CALL pliego.sp_edition_offer_set(u,edition,10.00,statement_timestamp()-INTERVAL '1 day',statement_timestamp()+INTERVAL '1 day',offer);
  RAISE EXCEPTION 'customer changed offer';
 EXCEPTION WHEN SQLSTATE 'P1004' THEN NULL; END;
 BEGIN
  CALL pliego.sp_edition_offer_set(a,edition,25.00,statement_timestamp()-INTERVAL '1 day',statement_timestamp()+INTERVAL '1 day',offer);
  RAISE EXCEPTION 'offer exceeds original price';
 EXCEPTION WHEN SQLSTATE 'P1001' THEN NULL; END;
 IF pliego.fn_offer_days_remaining('2026-10-07 02:00:00-05','2026-10-05 23:59:59-05')<>2 THEN RAISE EXCEPTION 'offer calendar days used elapsed duration'; END IF;
 IF NOT (pliego.fn_offer_ending_soon(3)) OR pliego.fn_offer_ending_soon(4) THEN RAISE EXCEPTION 'ending soon boundary incorrect'; END IF;
 IF (SELECT (f->>'count')::BIGINT FROM jsonb_array_elements(pliego.fn_offers_filter_options()->'categories') f WHERE f->>'slug'='offers-gate')<>1 THEN RAISE EXCEPTION 'offer facets ignored active offer'; END IF;
 CALL pliego.sp_cart_add_item(u,edition,2,cart,item,qty);
 SELECT * INTO quote FROM pliego.fn_cart_quote(u);
 IF quote.subtotal<>30.00 OR quote.tax_amount<>4.50 OR quote.total<>34.50 OR (quote.items->0->>'currentPrice')::NUMERIC<>15.00 THEN RAISE EXCEPTION 'cart ignored offer'; END IF;
 SELECT pickup_location_id INTO location FROM pliego.fn_pickup_locations() LIMIT 1;
 CALL pliego.sp_checkout_idempotent(u,key,NULL,'TRANSFER','APPROVED',cart,'STORE_PICKUP',location,o,state,pay,total,ref);
 IF total<>34.50 OR (SELECT precio_unitario FROM pliego.pedido_item WHERE pedido_id=o)<>15.00 THEN RAISE EXCEPTION 'checkout ignored offer'; END IF;
 CALL pliego.sp_edition_offer_clear(a,edition);
 IF pliego.fn_edition_price(edition)<>20.00 OR (SELECT offer_id FROM pliego.fn_edition_offer(edition)) IS NOT NULL THEN RAISE EXCEPTION 'inactive offer applied'; END IF;
 CALL pliego.sp_checkout_idempotent(u,key,NULL,'TRANSFER','APPROVED',cart,'STORE_PICKUP',location,replay,state,pay,total,ref);
 IF replay<>o OR total<>34.50 THEN RAISE EXCEPTION 'offer removal changed historical replay'; END IF;
 CALL pliego.sp_edition_offer_set(a,edition,10.00,statement_timestamp()-INTERVAL '1 day',statement_timestamp(),offer);
 IF pliego.fn_edition_price(edition)<>20.00 THEN RAISE EXCEPTION 'exclusive expiry boundary applied'; END IF;
 CALL pliego.sp_edition_offer_set(a,edition,10.00,statement_timestamp(),statement_timestamp()+INTERVAL '1 day',offer);
 IF pliego.fn_edition_price(edition)<>10.00 THEN RAISE EXCEPTION 'inclusive start boundary omitted'; END IF;
 CALL pliego.sp_edition_offer_set(a,edition,10.00,statement_timestamp()+INTERVAL '1 day',statement_timestamp()+INTERVAL '2 days',offer);
 IF pliego.fn_edition_price(edition)<>20.00 THEN RAISE EXCEPTION 'future offer applied'; END IF;
 CALL pliego.sp_edition_offer_set(a,edition,10.00,statement_timestamp()-INTERVAL '2 days',statement_timestamp()-INTERVAL '1 day',offer);
 IF pliego.fn_edition_price(edition)<>20.00 THEN RAISE EXCEPTION 'expired offer applied'; END IF;
 CALL pliego.sp_edition_offer_set(a,edition,10.00,statement_timestamp()-INTERVAL '1 day',statement_timestamp()+INTERVAL '1 day',offer);
 UPDATE pliego.edicion SET precio=8.00 WHERE edicion_id=edition;
 IF pliego.fn_edition_price(edition)<>8.00 OR (SELECT offer_id FROM pliego.fn_edition_offer(edition)) IS NOT NULL THEN RAISE EXCEPTION 'offer raised lowered base price'; END IF;
 CALL pliego.sp_edition_create(a,book,pub,'OFFERS-EBOOK',NULL,'es','EBOOK',NULL,NULL,12.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL,digital);
 CALL pliego.sp_edition_offer_set(a,digital,9.00,statement_timestamp()-INTERVAL '1 day',statement_timestamp()+INTERVAL '2 days','Ahorra en esta edición','Oferta limitada a esta edición',offer);
 CALL pliego.sp_edition_offer_set(a,edition,4.00,statement_timestamp()-INTERVAL '1 day',statement_timestamp()+INTERVAL '1 day',offer);
 IF (SELECT offer_copy FROM pliego.fn_edition_offer(digital))<>'Ahorra en esta edición' THEN RAISE EXCEPTION 'stored offer copy lost'; END IF;
 IF (SELECT edition_id FROM pliego.fn_catalog_search_offers(NULL,NULL,NULL,'offers-gate',NULL,NULL,NULL,NULL,NULL,'RELEVANCE',0,1))<>edition THEN RAISE EXCEPTION 'relevance sorting incorrect'; END IF;
 IF (SELECT edition_id FROM pliego.fn_catalog_search_offers(NULL,NULL,NULL,'offers-gate',NULL,NULL,NULL,NULL,NULL,'ENDING_SOON',0,1))<>edition THEN RAISE EXCEPTION 'expiry sorting incorrect'; END IF;
 IF (SELECT edition_id FROM pliego.fn_catalog_search_offers(NULL,NULL,NULL,'offers-gate',NULL,NULL,NULL,NULL,NULL,'PRICE_DESC',0,1))<>digital THEN RAISE EXCEPTION 'descending effective price sorting incorrect'; END IF;
 IF (SELECT edition_id FROM pliego.fn_catalog_search_offers(NULL,NULL,NULL,'offers-gate',NULL,NULL,NULL,NULL,NULL,'PRICE_ASC',1,1))<>digital THEN RAISE EXCEPTION 'effective-price pagination incorrect'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pliego.fn_catalog_search_offers(NULL,NULL,NULL,'offers-gate',NULL,NULL,NULL,NULL,'EBOOK','RELEVANCE',0,20) WHERE edition_id=digital AND total_count=1) THEN RAISE EXCEPTION 'product type filtering incorrect'; END IF;
 IF (SELECT (f->>'count')::BIGINT FROM jsonb_array_elements(pliego.fn_offers_filter_options()->'categories') f WHERE f->>'slug'='offers-gate')<>2 THEN RAISE EXCEPTION 'facet active count incorrect'; END IF;
 CALL pliego.sp_cart_add_item(u,digital,1,cart,item,qty);
 SELECT * INTO quote FROM pliego.fn_cart_quote(u);
 IF quote.subtotal<>9.00 OR quote.tax_amount<>1.35 OR quote.total<>10.35 THEN RAISE EXCEPTION 'digital offer ignored'; END IF;
 CALL pliego.sp_address_create(u,'Casa','Ana Pérez','Calle Ofertas',NULL,'Quito','Pichincha','EC',NULL,NULL,'+59325550134',TRUE,address);
 CALL pliego.sp_checkout_idempotent(u,uuidv4(),NULL,'TRANSFER','APPROVED',cart,'DIGITAL_ONLY',NULL,o,state,pay,total,ref);
 IF total<>10.35 THEN RAISE EXCEPTION 'digital checkout ignored offer'; END IF;
 CALL pliego.sp_category_create(a,'Padre de ofertas','offers-facet-parent',NULL,NULL,facet_parent);
 CALL pliego.sp_category_create(a,'Hija de ofertas','offers-facet-child',NULL,facet_parent,facet_child);
 UPDATE pliego.libro_categoria SET categoria_id=facet_child WHERE libro_id=book AND categoria_id=cat;
 CALL pliego.sp_category_set_status(a,facet_parent,'INACTIVE');
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(pliego.fn_offers_filter_options()->'categories') f WHERE f->>'slug' IN('offers-facet-parent','offers-facet-child')) THEN RAISE EXCEPTION 'offer facets exposed active child under inactive parent'; END IF;
 CALL pliego.sp_category_set_status(a,facet_parent,'ACTIVE');
 CALL pliego.sp_category_set_status(a,facet_child,'INACTIVE');
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(pliego.fn_offers_filter_options()->'categories') f WHERE f->>'slug' IN('offers-facet-parent','offers-facet-child')) THEN RAISE EXCEPTION 'offer facets counted inactive assigned child under active parent'; END IF;
END $gate$;
ROLLBACK;
